[versions]
dependencyUpdates = "0.52.0"
vanniktechPublish = "0.32.0"
gradlePluginPublish = "1.3.1"
buildConfig = "5.6.5"
commonsLang = "3.17.0"
gradleTooling = "8.14.1"
slf4j = "2.0.17"
bsp = "2.2.0-M2"
# tied to the bsp gson version
gson = "2.10.1"
junit = "5.12.2"
mokito = "5.18.0"
checkstyleTool = "10.24.0"

[libraries]
bsp = { module = "ch.epfl.scala:bsp4j", version.ref = "bsp" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
gradleTooling = { module = "org.gradle:gradle-tooling-api", version.ref = "gradleTooling" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
mokitoCore = { module = "org.mockito:mockito-core", version.ref = "mokito" }
mokitoJunit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mokito" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitLauncher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
mokito = ["mokitoCore", "mokitoJunit"]

[plugins]
# check for library updates
dependencyUpdates = { id = "com.github.ben-manes.versions", version.ref = "dependencyUpdates" }
# publish to Maven
vanniktechPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
# plugin publishing
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
# build config source generation
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
