import org.gradle.util.GradleVersion

plugins {
	id 'scala'
}

repositories {
	mavenCentral()
}

dependencies {
	// Gradle switched from `compile` to `implementation`
	if (GradleVersion.current().compareTo(GradleVersion.version("3.4")) >= 0)
		implementation('org.scala-lang:scala-library:2.12.16')
	else
		compile('org.scala-lang:scala-library:2.12.16')
}
