plugins {
    id 'application'
}

application {
    mainClass = 'org.sample.myapp.Main'
    applicationDefaultJvmArgs = ["-Dgreeting.language=en", "-Xmx16g"]
}

dependencies {
    implementation 'org.sample:number-utils:1.0'
    implementation 'org.sample:string-utils:1.0'
}

group 'org.sample'
version '1.0'

repositories {
    mavenCentral()
}